"""CtxRush Krea 2 Edit nodes for ComfyUI."""

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .nodes_multiref import (
    NODE_CLASS_MAPPINGS as _MULTIREF_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _MULTIREF_NAMES,
)

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **_MULTIREF_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **_MULTIREF_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
